micronaut:
  application:
    name: casaDoCodigo
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

server:
  port: 8080

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
