micronaut:
  application:
    name: casadocodigo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: admin
    password: secret
    dialect: POSTGRES
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#    dialect: H2
    minPoolSize: 1
    maxPoolSize: 10

jpa:
  default:
    entity-scan:
      packages: 'br.com.store.casa.codigo'
    properties:
      hibernate:
        hbm2dll:
          auto: update
      show_sql: true

flyway:
  datasources:
    default:
      enabled: true
#      locations: classpath:db/migration

endpoints:
  flyway:
    enabled: true
    sensitive: false